import { CardNode } from "../types.slint";
import { Constants } from "../constants.slint";
import { ListView } from "std-widgets.slint";

export component Card {
    in property <CardNode> card;
    in property <bool> show_answer;

    ListView {
        for i in 1: Text {
            text: show_answer ? card.answer : card.question;
            font-family: "Monospace";
            font-size: Constants.font_size_content;
            wrap: TextWrap.word-wrap;
            overflow: TextOverflow.elide;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}
