import { Constants } from "../constants.slint";
import { DeckNode } from "../types.slint";

export component Deck {
    in-out property <DeckNode> deck;
    in property <bool> shown;

    callback toggle();
    callback deck_clicked();

    HorizontalLayout {
        if shown: TouchArea {
            clicked => {
                deck_clicked();
            }
            HorizontalLayout {
                padding-left: (deck.level - 1) * Constants.padding_standard;
                HorizontalLayout {
                    alignment: start;
                    padding-top: Constants.padding_standard;
                    if deck.has_children: TouchArea {
                        Image {
                            source: deck.collapsed ? @image-url("../icons/angle_right.svg") : @image-url("../icons/angle_down.svg");
                        }

                        clicked => {
                            deck.collapsed = !deck.collapsed;
                            toggle();
                        }
                    }
                    Text {
                        text: deck.name;
                        font-family: Constants.font_family_standard;
                        font-size: Constants.font_size_content;
                        vertical-alignment: center;
                    }
                }

                HorizontalLayout {
                    alignment: end;
                    padding-top: Constants.padding_standard;
                    spacing: Constants.spacing_standard;

                    Text {
                        text: deck.new;
                        font-family: Constants.font_family_standard;
                        color: #808080;
                        font-size: Constants.font_size_subcontent;
                        vertical-alignment: center;
                    }

                    Text {
                        text: deck.learn;
                        font-family: Constants.font_family_standard;
                        color: #808080;
                        font-size: Constants.font_size_subcontent;
                        vertical-alignment: center;
                    }

                    Text {
                        text: deck.due;
                        font-family: Constants.font_family_standard;
                        color: #008000;
                        font-size: Constants.font_size_subcontent;
                        vertical-alignment: center;
                    }
                }
            }
        }
    }
}
