import { Constants } from "../constants.slint";
import { DeckNode } from "../types.slint";

export component Deck {
    in-out property <DeckNode> deck;
    in property <bool> shown;

    callback toggle();
    callback deck_clicked();

    HorizontalLayout {
        if shown: HorizontalLayout {
            padding-left: (deck.level - 1) * Constants.padding_standard;
            HorizontalLayout {
                alignment: start;
                padding-top: Constants.padding_standard;
                if deck.has_children: TouchArea {

                    Image {
                        source: deck.collapsed ? @image-url("../icons/angle_right.svg") : @image-url("../icons/angle_down.svg");
                    }

                    clicked => {
                        deck.collapsed = !deck.collapsed;
                        toggle();
                    }
                }
                TouchArea {
                    Text {
                        text: deck.name;
                        font-size: Constants.font_size_content;
                        vertical-alignment: center;
                    }

                    clicked => {
                        deck_clicked();
                    }
                }
            }

            HorizontalLayout {
                alignment: end;
                padding-top: Constants.padding_standard;
                spacing: Constants.spacing_standard;

                Text {
                    text: deck.new;
                    color: #808080;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }

                Text {
                    text: deck.learn;
                    color: #808080;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }

                Text {
                    text: deck.due;
                    color: #008000;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }
            }
        }
    }
}
