import { Constants } from "../constants.slint";

export component PageView {
    in property <[string]> pages;
    in-out property <int> current-page: 0;
    in property <int> total-pages: pages.length;

    changed pages => {
        current-page = 0;
    }

    sgr := SwipeGestureHandler {
        width: root.width;
        height: root.height;
        handle-swipe-down: current-page > 0;
        handle-swipe-up: current-page < total-pages - 1;
        swiped => {
            if self.current-position.y > self.pressed-position.y + self.height / 4 {
                if current-page > 0 {
                    current-page -= 1;
                }
            } else if self.current-position.y < self.pressed-position.y - self.height / 4 {
                if current-page < total-pages - 1 {
                    current-page += 1;
                }
            }
        }

        VerticalLayout {
            Text {
                text: (current-page < pages.length ? pages[current-page] : "") + (pages.length > 1 ? "\n\n(Page " + (current-page + 1) + " of " + total-pages + ")" : "");
                font-family: Constants.font_family_standard;
                font-size: Constants.font_size_content;
                wrap: TextWrap.word-wrap;
                overflow: TextOverflow.clip;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
