import { ListView } from "std-widgets.slint";
import { Deck } from "../components/deck.slint";
import { Constants, Translations } from "../constants.slint";
import { DeckNode, SyncState } from "../types.slint";

component Menu {
    in property <Translations> tr;
    in property <int> due;

    HorizontalLayout {
        VerticalLayout {
            alignment: start;
            spacing: Constants.spacing_standard;
            Text {
                text: "pbAnki";
                font-family: Constants.font_family_standard;
                font-size: Constants.font_size_heading;
                font-weight: 800;
            }

            Text {
                text: due + tr.cards_due_suffix;
                font-family: Constants.font_family_standard;
            }
        }

        HorizontalLayout {
            alignment: end;
            TouchArea {
                Image {
                    source: @image-url("../icons/reload.svg");
                }

                clicked => {
                }
            }
        }
    }
}

export component DeckSelectScreen {
    in property <Translations> tr;
    in property <int> due_total;
    in-out property <[DeckNode]> deck_nodes;

    callback deck_clicked(deck: DeckNode);

    VerticalLayout {
        Menu {
            due: due_total;
            tr: tr;
        }

        ListView {
            mouse-drag-pan-enabled: true;
            for deck[index] in deck_nodes: Deck {
                deck: deck;
                shown: deck_nodes[deck.parent_index].collapsed == false;
                toggle => {
                    deck_nodes[index].collapsed = !deck_nodes[index].collapsed;
                }
                deck_clicked => {
                    deck_clicked(deck);
                }
            }
        }
    }
}
