import { Constants } from "../constants.slint";
import { DeckNode } from "../types.slint";
import { Button } from "std-widgets.slint";

export component LearnScreen {
    in property <DeckNode> deck;

    callback home_clicked();

    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            HorizontalLayout {
                alignment: start;
                TouchArea {
                    Image {
                        source: @image-url("../icons/home.svg");
                    }

                    clicked => {
                        home_clicked();
                    }
                }
            }

            HorizontalLayout {
                alignment: center;
                spacing: 5px;

                Text {
                    text: deck.new;
                    color: #0000FF;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }

                Text {
                    text: deck.learn;
                    color: #FF0000;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }

                Text {
                    text: deck.due;
                    color: #008000;
                    font-size: Constants.font_size_subcontent;
                    vertical-alignment: center;
                }
            }

            HorizontalLayout {
                alignment: end;
                spacing: 5px;
                TouchArea {
                    Image {
                        source: @image-url("../icons/undo.svg");
                    }

                    clicked => {
                    }
                }

                TouchArea {
                    Image {
                        source: @image-url("../icons/redo.svg");
                    }

                    clicked => {
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            padding-top: Constants.padding_standard;
            Button {
                text: "Show Answer";

                clicked => {
                }
            }
        }
    }
}
