import { Constants } from "../constants.slint";
import { DeckNode, CardNode } from "../types.slint";
import { Button, ListView, ScrollView } from "std-widgets.slint";
import { RatingButton } from "../components/rating_button.slint";
import { PageView } from "../components/page_view.slint";

component Menu {
    in property <CardNode> card;
    callback home_clicked();

    HorizontalLayout {
        padding-bottom: Constants.padding_standard;
        HorizontalLayout {
            width: 33.33%;
            alignment: start;
            TouchArea {
                Image {
                    source: @image-url("../icons/home.svg");
                }

                clicked => {
                    home_clicked();
                }
            }
        }

        HorizontalLayout {
            width: 33.33%;
            alignment: center;
            spacing: Constants.spacing_standard;

            Text {
                text: card.deck.new;
                font-family: Constants.font_family_standard;
                color: #0000FF;
                font-size: Constants.font_size_subcontent;
                vertical-alignment: center;
            }

            Text {
                text: card.deck.learn;
                font-family: Constants.font_family_standard;
                color: #FF0000;
                font-size: Constants.font_size_subcontent;
                vertical-alignment: center;
            }

            Text {
                text: card.deck.due;
                font-family: Constants.font_family_standard;
                color: #008000;
                font-size: Constants.font_size_subcontent;
                vertical-alignment: center;
            }
        }

        HorizontalLayout {
            width: 33.33%;
            alignment: end;
            spacing: Constants.spacing_standard;
            TouchArea {
                Image {
                    source: @image-url("../icons/undo.svg");
                }

                clicked => {
                }
            }

            TouchArea {
                Image {
                    source: @image-url("../icons/redo.svg");
                }

                clicked => {
                }
            }
        }
    }
}

export component LearnScreen {
    in property <CardNode> card;
    in-out property <bool> show_answer;
    property <bool> valid_deck: card.question != ["No cards due!"] && card.answer != [];
    property <[string]> pages: show_answer ? card.answer : card.question;
    out property <int> current-page: 0;
    property <int> total-pages: pages.length;

    changed pages => {
        current-page = 0;
    }

    callback home_clicked();
    callback rate(rating: int);

    forward-focus: focus-scope;

    focus-scope := FocusScope {
        key-pressed(event) => {
            if valid_deck {
                if current-page > 0 && (event.text == Key.LeftArrow || event.text == Key.DownArrow || event.text == Key.PageDown) {
                    current-page -= 1;
                    accept
                } else if current-page < total-pages - 1 && (event.text == Key.RightArrow || event.text == Key.UpArrow || event.text == Key.PageUp) {
                    current-page += 1;
                    accept
                } else {
                    if !show_answer {
                        show_answer = true;
                        accept
                    } else {
                        if event.text == Key.LeftArrow || event.text == Key.DownArrow || event.text == Key.PageDown {
                            rate(0);
                            show_answer = false;

                            accept
                        } else if event.text == Key.RightArrow || event.text == Key.Return {
                            rate(1);
                            show_answer = false;

                            accept
                        } else if event.text == Key.Menu || event.text == Key.UpArrow || event.text == Key.PageUp {
                            rate(2);
                            show_answer = false;

                            accept
                        }
                    }
                }
            }
            reject
        }

        VerticalLayout {
            VerticalLayout {
                alignment: start;
                Menu {
                    card: card;
                    home_clicked => {
                        home_clicked();
                    }
                }

                PageView {
                    vertical-stretch: 1;
                    pages: pages;
                    current-page: current-page;
                    total-pages: total-pages;
                }
            }

            if valid_deck: VerticalLayout {
                alignment: end;
                HorizontalLayout {
                    alignment: center;
                    padding-top: Constants.padding_standard;

                    if !show_answer: Button {
                        width: self.preferred-width * 2;
                        height: self.preferred-height * 2;
                        text: "Show Answer";

                        clicked => {
                            show_answer = true;
                        }
                    }

                    if show_answer: HorizontalLayout {
                        spacing: Constants.spacing_medium;
                        for rating in 4: RatingButton {
                            duration: card.durations[rating];
                            label: rating == 0 ? "Again" : rating == 1 ? "Hard" : rating == 2 ? "Good" : "Easy";
                            color: rating == 0 ? #FF0000 : rating == 2 ? #008000 : rating == 3 ? #0000FF : #000000;

                            clicked => {
                                rate(rating);
                                show_answer = false;
                            }
                        }
                    }
                }
            }
        }
    }
}
