export global Constants {
    out property <string> font_family_standard: "Monospace";

    out property <length> font_size_heading: 30px;
    out property <length> font_size_content: 20px;
    out property <length> font_size_subcontent: 15px;

    out property <length> padding_standard: 20px;
    out property <length> spacing_standard: 5px;
    out property <length> spacing_medium: 10px;
}

export struct Translations {
	show_answer: string,
	again: string,
	hard: string,
	good: string,
	easy: string,
	cards_due_suffix: string,
	no_cards_due: string,
}
