import { Button } from "std-widgets.slint";
import { Constants } from "constants.slint"; 
import { Deck } from "deck.slint";

component Menu {
    in property <int> due;

    HorizontalLayout {
        VerticalLayout {
            alignment: start;
            spacing: 5px;
            Text {
                text: "pbAnki";
                font-size: Constants.font_size_heading;
                font-weight: 800;
            }

            Text {
                text: due + " cards due";
            }
        }

        HorizontalLayout {
            alignment: end;
            TouchArea {
                Image {
                    source: @image-url("./icons/reload.svg");
                }

                clicked => {
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    preferred-width: 500px;
    preferred-height: 400px;

    VerticalLayout {
        alignment: start;
        padding: Constants.padding_standard;
        Menu { }

        Deck {
            name: "Spanish Vocabulary";
        }

        Deck {
            name: "French Vocabulary";
        }
    }
}
